apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapplication1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapplication1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: webapplication1
    spec:
      containers:
      - name: webapplication1
        imagePullPolicy: Always
        image: mycontainerazure1974.azurecr.io/webapplication1:latest  # Replace with your image path
        ports:
        - containerPort: 8080
