name: Build and Push Docker Image

on:
  push:
    branches: [ master ]  # or any other branch you want to trigger on
  pull_request:
    branches: [ master ]

env:
  REGISTRY: mycontainerazure1974.azurecr.io  # Your Azure Container Registry
  IMAGE_NAME: my-dotnet-api  # Replace with your image name

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Azure Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}  # Set in GitHub secrets
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}  # Set in GitHub secrets

    - name: Build and Push Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile  # Path to your Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

    # Additional steps for deployment or other actions can be added here.
