name: workflow_02
on: [repository_dispatch]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggering Wokflow 2"
      - name: Checkout
        uses: actions/checkout@v2





#name: Build and Push Docker Image

#on:
  #push:
    #branches: [ master ]
  #pull_request:
    #branches: [ master ]

#env:
 # REGISTRY: mycontainerazure1974.azurecr.io
 # IMAGE_NAME: webapplication1
 # RESOURCE_GROUP: myRG
 # AKS_CLUSTER_NAME: mydotnet8webapiakscluster

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Azure Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.REGISTRY }}
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

    - name: Build and Push Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}:latest

